# Generated by Django 5.2.1 on 2025-05-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toggler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firewallrule',
            name='user',
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='udm_id',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
