# Generated by Django 5.2.1 on 2025-05-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toggler', '0002_remove_firewallrule_user_firewallrule_udm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewallrule',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
