# Generated by Django 5.2.1 on 2025-05-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toggler', '0003_firewallrule_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='xsrf_cookie',
            field=models.TextField(blank=True, null=True),
        ),
    ]
